services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    platform: linux/arm64
    container_name: keycloak
    command:
      - start-dev
      - --hostname=seaumsiddiqui.com
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --proxy=edge
      - --http-relative-path=/auth
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8088:8080"
    networks:
      - app-network
    restart: unless-stopped

  personalblog-api:
    image: seaumsiddiqui0/personalblog-api:latest  # <-- Pull from Docker Hub
    platform: linux/arm64
    container_name: personalblog-api
    ports:
      - "9099:9090"
    depends_on:
      - keycloak
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_AUTH_CONVERTER_RESOURCE_ID: ${JWT_AUTH_CONVERTER_RESOURCE_ID}
      JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE: ${JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS}
      ORACLE_CLOUD_CONFIG_PATH: ${ORACLE_CLOUD_CONFIG_PATH}
    volumes:
      - ./config:/config:ro
    networks:
      - app-network
    restart: unless-stopped

  personalblog-ui:
    image: seaumsiddiqui0/personalblog-ui:latest # <-- Pull from Docker Hub
    platform: linux/arm64
    container_name: personalblog-ui
    ports:
      - "8080:80"
    depends_on:
      - personalblog-api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
