spring:
  config:
    activate:
      on-profile: prod

  # ---------------- Datasource (PostgreSQL) ----------------
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ------------ JPA / Hibernate Settings -------------
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # Production: validate schema (no auto create/update)
    show-sql: false        # Disable SQL logging in production
    properties:
      hibernate:
        format_sql: false  # Don't format SQL in logs (improves performance)

  # ----------- Multipart File Upload Limits -----------
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}      # "10MB" max file size
      max-request-size: ${MAX_REQUEST_SIZE:10MB} # "10MB" max request size (multipart/form-data)

  # ----------- Security (JWT/OAuth2) -----------
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

# -------------- CORS Configuration --------------
# Adjust allowed origins for your frontend. In PROD, set APP_ALLOWED_ORIGINS to your actual domain.
# You can also use spring.mvc.cors.allowed-origins or allowed-origins-patterns (wildcards) as needed:contentReference[oaicite:10]{index=10}.
app:
  cors:
    allowed-origins: ${APP_ALLOWED_ORIGINS:http}
    # Example: to use your production domain, set APP_ALLOWED_ORIGINS=https://myblog.example.com
    # (Alternatively use wildcard patterns like https://*.example.com in allowed-origins-patterns)

# -------------- Keycloak realm Configuration --------------
jwt:
  auth:
    converter:
      resource-id: personalblog_server
      principal-attribute: preferred_username

# ----------- Oracle Cloud (OCI) Configuration ----------
oracle:

  config:
    path: ${ORACLE_CLOUD_CONFIG_PATH}
  cloud:
    region: ap-mumbai-1
    namespace: bmihpqq11x49
    bucket-name: blog-image-bucket-20241130-2238

# ------------- Server running port ------------
server:
  port: 9090  # Application will run on port :9090
